#!/bin/sh
# profile file, runs on login

# env
XDG_CONFIG_HOME="$HOME/.local/etc"
source "$XDG_CONFIG_HOME/.sh/env"

# startx only if:
# 1. tty1
# 2. xorg not exist
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
