#!/bin/zsh
# profile file, runs on login

# var
XDG_CONFIG_HOME="$HOME/.local/etc"
source "$XDG_CONFIG_HOME/.sh/var"

# start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
