#!/bin/sh

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ source
source $XDG_CONFIG_HOME/.sh/env
source $XDG_CONFIG_HOME/.sh/alias
source $XDG_CACHE_HOME/mdf/m_sh

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cd $home
if [[ $PWD == $HOME ]]
then
	cd $home
fi

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ misc
stty stop undef
# prevent ctrl-s to freeze terminal
