#!/bin/sh

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ $path & $dir
path=$(readlink -f "$0")
# absolute path to this script
dir=$(dirname "$path")
# absolute path this script is in

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ env
source $dir/.config/sh/.env

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ shopt
shopt -s dotglob
# loop hidden files

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ XDG_CONFIG_HOME
mkdir -p "$XDG_CONFIG_HOME"
cd $dir/.config
for i in *; do
	rm -rf					"$XDG_CONFIG_HOME/$i"
	ln -s "$PWD/$i"			"$XDG_CONFIG_HOME/$i"
done

ln -sf "$XDG_CONFIG_HOME/sh/.env"		"$HOME/.env"
ln -sf "$XDG_CONFIG_HOME/sh/.profile"		"$HOME/.profile"
ln -sf "$XDG_CONFIG_HOME/sh/.profile"		"$HOME/.zprofile"
ln -sf "$XDG_CONFIG_HOME/sh/.shrc"		"$HOME/.shrc"
ln -sf "$XDG_CONFIG_HOME/bash/.bashrc"		"$HOME/.bashrc"
ln -sf "$XDG_CONFIG_HOME/x11/.xprofile"		"$HOME/.xprofile"
# ln -sf "$XDG_CONFIG_HOME/vim/.vimrc"		"$HOME/.vimrc"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ XDG_CACHE_HOME
mkdir -p "$XDG_CACHE_HOME"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ XDG_DATA_HOME
mkdir -p "$XDG_DATA_HOME"
cd $dir/.local/share
for i in *; do
	rm -rf					"$XDG_DATA_HOME/$i"
	ln -s "$PWD/$i"			"$XDG_DATA_HOME/$i"
done

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ XDG_STATE_HOME
mkdir -p "$XDG_STATE_HOME"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ XDG_EXE_HOME
mkdir -p "$XDG_EXE_HOME"
cd $dir/.local/bin
for i in *; do
	rm -rf					"$XDG_EXE_HOME/$i"
	ln -s "$PWD/$i"			"$XDG_EXE_HOME/$i"
done
