#!/bin/sh

# dark-light switch

mode=${1:-0}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ xresources
if [ "$mode" == 0 ]
then
	# sed -e '/solarized-dark/,/solarized-dark/s/! \(.\+\)/\1/'	\
	#     -e '/solarized-set/,/solarized-set/s/! \(.\+\)/\1/'	\
	#     "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
	# sed -e '/nord-dark/,/nord-dark/s/! \(.\+\)/\1/'	\
	#     -e '/nord-set/,/nord-set/s/! \(.\+\)/\1/'	\
	#     "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
	# sed -e '/penumbra-dark1/,/penumbra-dark1/s/! \(.\+\)/\1/'	\
	#     -e '/penumbra-set/,/penumbra-set/s/! \(.\+\)/\1/'	\
	#     "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
	sed -e '/simple-dark-solarized/,/simple-dark-solarized/s/! \(.\+\)/\1/'	\
	    -e '/simple-set/,/simple-set/s/! \(.\+\)/\1/'	\
	    "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
else
	# sed -e '/solarized-light/,/solarized-light/s/! \(.\+\)/\1/'	\
	#     -e '/solarized-set/,/solarized-set/s/! \(.\+\)/\1/'	\
	#     "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
	# sed -e '/penumbra-light0/,/penumbra-light0/s/! \(.\+\)/\1/'	\
	#     -e '/penumbra-set/,/penumbra-set/s/! \(.\+\)/\1/'	\
	#     "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
	sed -e '/simple-light-solarized/,/simple-light-solarized/s/! \(.\+\)/\1/'	\
	    -e '/simple-set/,/simple-set/s/! \(.\+\)/\1/'	\
	    "$XDG_CONFIG_HOME/x11/.Xresources" | xrdb 2> /dev/null
fi

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ gtk
if [ "$mode" == 0 ]
then
	rm -rf "$XDG_CONFIG_HOME/gtk-3.0"
	mkdir -p "$XDG_CONFIG_HOME/gtk-3.0"
	cp "$aidan_git/arch_config/.config/gtk-3.0/settings.ini"	"$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
else
	rm -rf "$XDG_CONFIG_HOME/gtk-3.0"
	mkdir -p "$XDG_CONFIG_HOME/gtk-3.0"
	cp "$aidan_git/arch_config/.config/gtk-3.0/settings.ini"	"$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
	echo "gtk-theme-name=Adwaita" >> "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
fi

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ zathura
if [ "$mode" == 0 ]
then
	rm -rf "$XDG_CONFIG_HOME/zathura"
	mkdir -p "$XDG_CONFIG_HOME/zathura"
	cp "$aidan_git/arch_config/.config/zathura/zathurarc"	"$XDG_CONFIG_HOME/zathura/zathurarc"
else
	rm -rf "$XDG_CONFIG_HOME/zathura"
	mkdir -p "$XDG_CONFIG_HOME/zathura"
	cp "$aidan_git/arch_config/.config/zathura/zathurarc"	"$XDG_CONFIG_HOME/zathura/zathurarc"
	echo "set recolor false" >> "$XDG_CONFIG_HOME/zathura/zathurarc"
fi

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ renew dwm
export WM="dwm"

wmpid(){
	tree="$(pstree -ps $$)"
	tree="${tree#*$WM(}"
	echo "${tree%%)*}"
}

kill -HUP "$(wmpid)"
exit 1
# steal code from sysact
