#!/bin/sh

# give command better default
alias ls="ls -Ah1v --group-directories-first --color=auto"
# -p
alias chmod="chmod --preserve-root -v"
alias chown="chown --preserve-root -v"
alias df="df -h"
alias du="du -h"
alias mkdir="mkdir -p"
# alias grep="grep --color=auto"
# alias diff="diff --color=auto"

# abbreviate long command
alias v="vim"
alias ed="emacs --daemon"
alias ek="emacsclient -e '(kill-emacs)'"
alias ke="kill $(pidof emacs)"
# alias e="emacsclient -nw -a ''"
# alias E="emacs -nw"
# alias e="devour emacsclient -c"
# alias E="devour emacs"
alias e="emacsclient -nw"
alias E="emacs -nw"
alias lf="lfub"
alias ll="ls -l"
alias pacref="reflector --country 'China' --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist"

# abbreviate git command
alias gs="git status -s"
alias gd="git diff"
alias gl="git log --all --oneline --graph"

alias ga="git add --all"
alias gc="git commit -m -"
alias gca="git commit --amend"
alias gp="git push"

alias gccs="git config credential.helper store"
alias gsl="find . -maxdepth 1 -mindepth 1 -type d -exec sh -c '(echo {} && cd {} && git status -s && echo)' \;"
# https://stackoverflow.com/a/65970494
