#!/bin/zsh
# profile file, runs on login

# var
source $HOME/.config/.sh/var

# if doesn't exist shortcutrc, run shortcuts script
[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/.sh/shortcutrc ] && setsid shortcuts >/dev/null 2>&1

# start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
