#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
output=`xrandr | grep "\bconnected\b" | cut -d' ' -f1`
xrandr --output $output --set TearFree on
xset s off dpms 2700 2700 2700	# disable screen saver blanking & set dpms. https://wiki.archlinux.org/title/Display_Power_Management_Signaling#Modify_DPMS_and_screensaver_settings_with_a_command

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info

autostart="mpd dunst unclutter pipewire nutstore"
for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

fcitx5 -d		# run fcitx5 as daemon

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
