# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme-dark.toml
# https://yazi-rs.github.io/docs/configuration/theme

# "black":    terminal color code 0
# "white":    terminal color code 15
# "gray":     terminal color code 7
# "darkgray": terminal color code 8

[flavor]

dark  = ""
light = ""

[app]

overall = {}

[mgr]

cwd = {}

# find
find_keyword  = {}
find_position = {}

# symlink
symlink_target = {}

# marker
marker_copied   = {fg = "yellow", bg = "yellow"}
marker_cut      = {fg = "red",    bg = "red"}
marker_marked   = {fg = "green",  bg = "green"}
marker_selected = {fg = "white",  bg = "white"}
marker_symbol   = ""

# count
count_copied   = {fg = "black", bg = "yellow"}
count_cut      = {fg = "black", bg = "red"}
count_selected = {fg = "black", bg = "white"}

# border
border_symbol = " "
border_style  = {}

# highlighting
# syntect_theme = "~/.config/yazi/theme_preview.tmTheme"

[tabs]

active   = {reversed = true}
inactive = {fg = "white", bg = "black"}

sep_inner = {open = "", close = ""}
sep_outer = {open = "", close = ""}

[mode]

normal_main = {fg = "white", bg = "black"}
normal_alt  = {fg = "white", bg = "black"}
select_main = {fg = "white", bg = "black"}
select_alt  = {fg = "white", bg = "black"}
unset_main  = {fg = "white", bg = "black"}
unset_alt   = {fg = "white", bg = "black"}

[indicator]

parent = {reversed = true}
current = {reversed = true}
preview = {underline = true}
padding = {open = "█", close = "█"}

[status]

overall   = {}
sep_left  = {open = "", close = ""}
sep_right = {open = "", close = ""}

# permissions
perm_sep   = {}
perm_type  = {}
perm_read  = {}
perm_write = {}
perm_exec  = {}

# progress
progress_label  = {}
progress_normal = {fg = "blue", bg = "black"}
progress_error  = {fg = "red",  bg = "black"}

[which]

cols            = 1
mask            = {}
cand            = {}
rest            = {}
desc            = {}
separator       = "    "
separator_style = {}

[confirm]

border     = {}
title      = {}
body       = {}
list       = {}
btn_yes    = {reversed = true}
btn_no     = {}
btn_labels = ["y", "n"]

[spot]

border = {}
title  = {}

# table
tbl_col  = {}
tbl_cell = {reversed = true}

[notify]

title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

[pick]

border   = {}
active   = {}
inactive = {}

[input]

border   = {}
title    = {}
value    = {}
selected = {}

[cmp]

border   = {}
active   = {reversed = true}
inactive = {}

# icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]

border  = {}
title   = {}
hovered = {}

[help]

on      = {}
run     = {}
desc    = {}
hovered = {reversed = true}
footer  = {}

[filetype]

# file --mime-type cat_white.jpg

rules = [

	{url = "*/", fg = "blue"},

	{url = "*", is = "link",   fg = "cyan"},
	{url = "*", is = "orphan", fg = "red"},
	{url = "*", is = "exec",   fg = "green"},

	{url = "*.zip",  fg = "magenta"},
	{url = "*.7z",   fg = "magenta"},
	{url = "*.rar",  fg = "magenta"},
	{url = "*.tar",  fg = "magenta"},
	{url = "*.gz",   fg = "magenta"},

	{url = "*.jpg",  fg = "yellow"},
	{url = "*.png",  fg = "yellow"},
	{url = "*.mp3",  fg = "yellow"},
	{url = "*.mp4",  fg = "yellow"},
	{url = "*.mkv",  fg = "yellow"},
	{url = "*.pdf",  fg = "yellow"},
	{url = "*.epub", fg = "yellow"},
	{url = "*.mobi", fg = "yellow"},
	{url = "*.azw3", fg = "yellow"},

	{url = "**/dir", fg = "yellow"},
	{url = "*.info*", fg = "yellow"},

	# {mime = "application/zip",              fg = "magenta"},
	# {mime = "application/7z-compressed",    fg = "magenta"},
	# {mime = "application/rar",              fg = "magenta"},
	# {mime = "image/*",                      fg = "yellow"},
	# {mime = "audio/*",                      fg = "yellow"},
	# {mime = "video/*",                      fg = "yellow"},
	# {mime = "application/pdf",              fg = "yellow"},
	# {mime = "application/epub+zip",         fg = "yellow"},
	# {mime = "application/mobipocket-ebook", fg = "yellow"},

]

[icon]

globs = []
dirs  = []
files = []
exts  = []
conds = []
