[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
scrolloff = 0

[preview]
tab_size = 8
max_width = 10000
max_height = 10000

[opener]
# default = [
# 	{ run = 'xdg-open "$@"', block = true },
# ]

archive = [ { run = 'ouch decompress "$@"', block = true }, ]
audio   = [ { run = 'mpv "$@"', block = true }, ]
dir     = [ { run = 'nvim "$@"', block = true }, ]
image   = [ { run = 'nsxiv -a "$@"' }, ]
pdf     = [ { run = 'zathura "$@"' }, ]
text    = [ { run = 'nvim "$@"', block = true }, ]
video   = [ { run = 'mpv "$@"', block = true }, ]

[open]
# rules = [
# 	{ name = "*", use = [ "default" ] },
# ]
rules = [
	{ name = "*/", use = "dir" },

	{ mime = "application/pdf", use = "pdf" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = "archive" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },

	{ name = "*", use = "text" },
]

[tasks]

[plugin]
prepend_fetchers = [
	{id = "git", name = "*", run = "git"},
	{id = "git", name = "*/", run = "git"},
]
append_fetchers = [
]
prepend_previewers = [
	{mime = "text/diff",              run = 'code'},
	{mime = "text/*",                 run = 'piper -- cat "$1"'},
	{mime = "application/javascript", run = 'piper -- cat "$1"'},
]
append_previewers = [
	{name = "*", run = 'piper -- hexyl "$1"'},
]

[input]
# find_origin = "bottom-left"

[pick]

[which]

[log]

[headsup]
