[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
scrolloff = 0

[preview]
tab_size = 8
max_width = 10000
max_height = 10000

# [opener]
# default = [
# 	{ run = 'xdg-open "$@"', block = true },
# ]

# [open]
# rules = [
# 	{ name = "*", use = [ "default" ] },
# ]

[tasks]

[plugin]
prepend_fetchers = [
	{id = "git", name = "*", run = "git"},
	{id = "git", name = "*/", run = "git"},
]
append_fetchers = [
]
prepend_previewers = [
	{mime = "text/diff",              run = 'code'},
	{mime = "text/*",                 run = 'piper -- cat "$1"'},
	{mime = "application/javascript", run = 'piper -- cat "$1"'},
]
append_previewers = [
	{name = "*", run = 'piper -- hexyl "$1"'},
]

[input]
# find_origin = "bottom-left"

[pick]

[which]

[log]

[headsup]
