source ~/a_sr/config/zsh/env.zsh

source $a_sr/config/zsh/zim.zsh

source $a_sr/config/zsh/alias.zsh
source $a_sr/config/zsh/vi.zsh
source $a_sr/config/zsh/fzf.zsh

source $a_sr/config/zsh/completion.zsh
source $a_sr/config/zsh/key-bindings.zsh

setopt auto_cd
cdpath=($HOME $a $a_co $a_cs $a_io $a_ll)
setopt HIST_IGNORE_ALL_DUPS

WORDCHARS=${WORDCHARS//[\/]}
# Remove path separator from WORDCHARS.
