source ~/Aidan/FD/config/zsh/env.zsh

source $AIDAN_FD/config/zsh/zim.zsh

source $AIDAN_FD/config/zsh/alias.zsh
source $AIDAN_FD/config/zsh/vi.zsh
source $AIDAN_FD/config/zsh/fzf.zsh

source $AIDAN_FD/config/zsh/completion.zsh
source $AIDAN_FD/config/zsh/key-bindings.zsh

setopt auto_cd
cdpath=($HOME $AIDAN $AIDAN/_ $AIDAN_AC $AIDAN_ED $AIDAN_FD)
setopt HIST_IGNORE_ALL_DUPS

WORDCHARS=${WORDCHARS//[\/]}
# Remove path separator from WORDCHARS.
