cmap ;xco /home/aidan/.config
cmap ;xca /home/aidan/.cache
cmap ;xda /home/aidan/.local/share
cmap ;a /home/ai
cmap ;c /home/ai/a_gi/conf
cmap ;aid /home/ai/a/id
cmap ;agi /home/ai/a_gi
cmap ;f /home/aidan/.config/.sh/bm-files
cmap ;d /home/aidan/.config/.sh/bm-dirs
cmap ;x /home/aidan/.config/.x11/xresources
cmap ;z /home/aidan/.config/zsh/.zshrc
cmap ;v /home/aidan/.config/.vim/.vimrc
cmap ;l /home/aidan/.config/lf/lfrc
cmap ;n /home/ai/a/in/0.md
